DO ,1 <- #9
DO ,2 <- #8
PLEASE DO ,1 SUB #1 <- #0
PLEASE ABSTAIN FROM DOING ,1
DO ,3 <- #0
PLEASE ABSTAIN FROM DOING ,3
DO ,4 <- #1
PLEASE ABSTAIN FROM DOING ,4
DO ,5 <- #0
PLEASE ABSTAIN FROM DOING ,5
DO ,6 <- #1
PLEASE ABSTAIN FROM DOING ,6
DO ,7 <- #0
PLEASE ABSTAIN FROM DOING ,7
PLEASE READ OUT ,3
PLEASE GIVE UP
