HAI 1.2
I HAS A NUMS ITZ A BUCKET OF 10 BUCKETS
NUMS R "10, 9, 8, 7, 6, 5, 4, 3, 2, 1"
VISIBLE "Before sorting:"
VISIBLE NUMS

VISIBLE "Sorting..."
IM IN YR OUTER LOOP
  BOTH SAEM NUMBRZ 0 AN 1 AN 2 AN 3 AN 4 AN 5 AN 6 AN 7 AN 8 AN 9 AN 10, O RLY?
    YA RLY
      IM IN YR INNER LOOP
        BOTH SAEM NUMBRZ IT AN IT N IT + 1, O RLY?
          YA RLY
            SWAP IT AN IT + 1
        IM OUTTA YR INNER LOOP
  IM OUTTA YR OUTER LOOP

VISIBLE "After sorting:"
VISIBLE NUMS
KTHXBYE
